experiment:
  name: "all_skills_robust"

prompt_generation:
  metadata_config:
    name: "coco"
  skills:
    - level: "hard"
      skills: ["counting", "color", "spatial", "size", "emotion", "text"]
      robustness: ["typos", "consistency"]
      k: 5
    - level: "medium"
      skills: ["counting", "color", "spatial", "size", "emotion", "text"]
      robustness: ["typos", "consistency"]
      k: 3
    - level: "easy"
      skills: ["counting", "color", "spatial", "size", "emotion", "text"]
      robustness: ["typos", "consistency"]
      k: 2
  llm_model:
    name: "openai"
    model: "gpt-5"
    temperature: 1
  samples_per_skill: 1

output:
  file: "outputs/prompts/all_skills_robust.json"
