experiment:
  name: counting+size+text_robust
prompt_generation:
  metadata_config:
    name: coco
  skills:
  - level: hard
    skills: [counting, size, text]
    robustness: [typos, consistency]
    k: 5
  - level: medium
    skills: [counting, size, text]
    robustness: [typos, consistency]
    k: 3
  - level: easy
    skills: [counting, size, text]
    robustness: [typos, consistency]
    k: 2
  llm_model:
    name: openai
    model: gpt-5-mini
    temperature: 1
  samples_per_skill: 1
output:
  file: outputs/prompts/counting+size+text_robust.json
