experiment:
  name: counting+color+spatial+size
prompt_generation:
  metadata_config:
    name: coco
  skills:
  - level: hard
    skills: [counting, color, spatial, size]
    k: 5
  - level: medium
    skills: [counting, color, spatial, size]
    k: 3
  - level: easy
    skills: [counting, color, spatial, size]
    k: 2
  llm_model:
    name: openai
    model: gpt-5-mini
    temperature: 1
  samples_per_skill: 1
output:
  file: outputs/prompts/counting+color+spatial+size.json
