experiment:
  name: "color+size2"

prompt_generation:
  metadata_config:
    name: "coco"
  skills:
    - level: "medium"
      skills: ["color", "size"]
      k: 2
  llm_model:
    name: "openai"
    model: "gpt-4"
    temperature: 1.5
  samples_per_skill: 1

output:
  file: "outputs/prompts/color+size2.json"
