experiment:
  name: "full"

prompt_generation:
  metadata_config:
    name: "coco"
  skills:
    - level: "medium"
      skills: ["counting", "color", "spatial", "size", "emotion", "text"]
      k: 2
  llm_model:
    name: "openai"
    model: "gpt-4"
    temperature: 1.5
  samples_per_skill: 10

output:
  file: "outputs/prompts/all_skills.json"
